groups:
  - name: churn_prediction_alerts
    interval: 30s
    rules:
      - alert: HighPredictionLatency
        expr: histogram_quantile(0.95, rate(churn_prediction_latency_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High prediction latency detected"
          description: "95th percentile latency is above 1 second"
      
      - alert: ManyHighRiskCustomers
        expr: churn_high_risk_customers > 50
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Many high-risk customers detected"
          description: "More than 50 high-risk customers in current batch"
      
      - alert: APIDown
        expr: up{job="churn-prediction-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Churn Prediction API is down"
          description: "The API has been down for more than 1 minute"